### ISSUE TITLE
cannot import fusions

### ISSUE THREAD

**Issue by datar001** [doc-doc/NExT-QA#1]
Hi, Thanks for you share. It's a beautiful work. But it seems to have a problem when i run this code.

Traceback (most recent call last):
  File "main_qa.py", line 1, in <module>
    from videoqa import *
  File "/media/ubuntu/HDD/zcy/NExT-QA-main/videoqa.py", line 2, in <module>
    from networks.VQAModel import EVQA, STVQA, CoMem, HME, HGA
  File "/media/ubuntu/HDD/zcy/NExT-QA-main/networks/VQAModel/HGA.py", line 7, in <module>
    from block import fusions #pytorch >= 1.1.0
ImportError: cannot import name 'fusions'

It seems to be lack of a file named 'block.py' in the network folder.

**Comment by doc-doc** [comment]
Hi, please make sure you have successfully installed the following two libs:

block==0.0.5
block.bootstrap.pytorch==0.1.6

**Comment by datar001** [comment]
> Hi, please make sure you have successfully installed the following two libs:
> 
> block==0.0.5
> block.bootstrap.pytorch==0.1.6

**Comment by datar001** [comment]
I have installed these libs:
![image](https://user-images.githubusercontent.com/62345916/121547843-15a7c900-ca3f-11eb-89b1-7be1e03d8e52.png)

And I install all libs according to the requirements.txt.

**Comment by doc-doc** [comment]
Okay, are you using the right env for this repo?  You can also check by vim a clean '.py' file and test:
```
from block import fusions
```
If it throws errors, then you have to re-install the libs.

**Comment by datar001** [comment]
The environment was achieved by the guidance in this repo. It seems to be right. 
python 3.6.8, torch1.6.0
I test this line in the python console and it also outputs the mistake.
![image](https://user-images.githubusercontent.com/62345916/121550494-5dc7eb00-ca41-11eb-9064-5a878979404d.png)

Then i re-install the libs, it still outputs this mistake.
![image](https://user-images.githubusercontent.com/62345916/121550738-936cd400-ca41-11eb-8fae-40be5ca6ee0a.png)

**Comment by doc-doc** [comment]
Not sure the problem here, perhaps you have to create a new env and setup the environment strictly following my guideline.

**Comment by datar001** [comment]
I have solved this problem just now. It seems to be caused by pip resource. 
When I re-install block and block.bootstrap.pytorch from mirrors.aliyun.com/pypi/simple rather than pypi.tuna.tsinghua.edu.cn/simple, this code runs well.

**Comment by doc-doc** [comment]
Great.

**Comment by andlyu** [comment]
@datar001, could you share the commands you used to "re-install block and block.bootstrap.pytorch from mirrors.aliyun.com/pypi/simple" ?

-Thanks for the discussion

**Comment by doc-doc** [comment]
Pls try this:
```
pip install -i https://mirrors.aliyun.com/pypi/simple block==0.0.5

pip install -i https://mirrors.aliyun.com/pypi/simple block.bootstrap.pytorch==0.1.6
```

**Comment by andlyu** [comment]
Thanks. I had to first install block and then block.bootstrap.pytorch from https://mirrors.aliyun.com/pypi/simple before loading from requirements.txt. (block and block.bootstrap.pytorch were commented out) And then it worked. Thanks again.

**Comment by RedContritio** [comment]
I found it's possible that `block.bootstrap.pytorch` is shadowed by package `block`, but there is no `fusions` in `block` package.

**As a solution**:

1. uninstall `block` and `block.bootstrap.pytorch` first.
2. install from [source](https://github.com/Cadene/block.bootstrap.pytorch)

then `fusions` can be found.

**Suggestions**

I think `block` may be not necessary in project, while `block.bootstrap.pytorch` is installed, so maybe remove it from requirements is a better choice.

**Comment by GaoR311** [comment]
<img width="1809" height="660" alt="Image" src="https://github.com/user-attachments/assets/c14d3199-78f6-4116-842f-35a365349df1" />
How can I solve this? Please help!

**Comment by GaoR311** [comment]
<img width="1803" height="665" alt="Image" src="https://github.com/user-attachments/assets/6603c191-c999-4f0a-8da6-7741ff280203" />
How can I solve this? Please help!
